language: go

go:
  - 1.11.x

install:
  - go get github.com/alecthomas/gometalinter
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

before_script:
  - gometalinter --install --update

script:
  # Execute static checks
  - gometalinter --cyclo-over=13 --vendor ./...

# Execute tests and generate coverage for all the packages except fakes and tests
  - make test
  - goveralls -coverprofile profile.cov -service=travis-ci

notifications:
  slack: openservicebrokerapi:KQo2QAC6LXeEeXPOemOXja48
