// Code generated by counterfeiter. DO NOT EDIT.
package platformfakes

import (
	sync "sync"

	platform "github.com/Peripli/service-broker-proxy/pkg/platform"
	types "github.com/Peripli/service-manager/pkg/types"
)

type FakeSMVisibilityConverter struct {
	ConvertStub        func(*types.Visibility, *types.ServicePlan) ([]*platform.ServiceVisibilityEntity, error)
	convertMutex       sync.RWMutex
	convertArgsForCall []struct {
		arg1 *types.Visibility
		arg2 *types.ServicePlan
	}
	convertReturns struct {
		result1 []*platform.ServiceVisibilityEntity
		result2 error
	}
	convertReturnsOnCall map[int]struct {
		result1 []*platform.ServiceVisibilityEntity
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSMVisibilityConverter) Convert(arg1 *types.Visibility, arg2 *types.ServicePlan) ([]*platform.ServiceVisibilityEntity, error) {
	fake.convertMutex.Lock()
	ret, specificReturn := fake.convertReturnsOnCall[len(fake.convertArgsForCall)]
	fake.convertArgsForCall = append(fake.convertArgsForCall, struct {
		arg1 *types.Visibility
		arg2 *types.ServicePlan
	}{arg1, arg2})
	fake.recordInvocation("Convert", []interface{}{arg1, arg2})
	fake.convertMutex.Unlock()
	if fake.ConvertStub != nil {
		return fake.ConvertStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.convertReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSMVisibilityConverter) ConvertCallCount() int {
	fake.convertMutex.RLock()
	defer fake.convertMutex.RUnlock()
	return len(fake.convertArgsForCall)
}

func (fake *FakeSMVisibilityConverter) ConvertCalls(stub func(*types.Visibility, *types.ServicePlan) ([]*platform.ServiceVisibilityEntity, error)) {
	fake.convertMutex.Lock()
	defer fake.convertMutex.Unlock()
	fake.ConvertStub = stub
}

func (fake *FakeSMVisibilityConverter) ConvertArgsForCall(i int) (*types.Visibility, *types.ServicePlan) {
	fake.convertMutex.RLock()
	defer fake.convertMutex.RUnlock()
	argsForCall := fake.convertArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSMVisibilityConverter) ConvertReturns(result1 []*platform.ServiceVisibilityEntity, result2 error) {
	fake.convertMutex.Lock()
	defer fake.convertMutex.Unlock()
	fake.ConvertStub = nil
	fake.convertReturns = struct {
		result1 []*platform.ServiceVisibilityEntity
		result2 error
	}{result1, result2}
}

func (fake *FakeSMVisibilityConverter) ConvertReturnsOnCall(i int, result1 []*platform.ServiceVisibilityEntity, result2 error) {
	fake.convertMutex.Lock()
	defer fake.convertMutex.Unlock()
	fake.ConvertStub = nil
	if fake.convertReturnsOnCall == nil {
		fake.convertReturnsOnCall = make(map[int]struct {
			result1 []*platform.ServiceVisibilityEntity
			result2 error
		})
	}
	fake.convertReturnsOnCall[i] = struct {
		result1 []*platform.ServiceVisibilityEntity
		result2 error
	}{result1, result2}
}

func (fake *FakeSMVisibilityConverter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.convertMutex.RLock()
	defer fake.convertMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSMVisibilityConverter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ platform.SMVisibilityConverter = new(FakeSMVisibilityConverter)
