name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get github.com/alecthomas/gometalinter
        go get golang.org/x/tools/cmd/cover
        go get github.com/mattn/goveralls
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        gometalinter --install --update

    - name: Test
      run: make test
